### ISSUE TITLE
Fails during stack creation

### ISSUE THREAD

**Issue by peegee123** [aws-samples/aws-organizations-tag-inventory#14]
I've managed to create the Central stack but when I try to create a Spoke I get this failure:

aws-organizations-tag-inventory-spoke-stack: creating CloudFormation changeset...
10:59:42 | CREATE_FAILED        | Custom::ResourceExplorerIndex    | spokeMyIndexresour...omresource40170C84
Received response status [FAILED] from custom resource. Message returned: Region is missing

Logs: /aws/lambda/aws-organizations-tag-inv-comamazonawscdkcustomres-fQHE9mOINjVY

at resolveRegionConfig (/opt/nodejs/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:9:15)
at new ResourceExplorer2Client (/opt/nodejs/node_modules/@aws-sdk/client-resource-explorer-2/dist-cjs/ResourceExplorer2Client.js:22:69)
at turnOnIndexForRegion (/var/task/index.js:2626:54)
at Runtime.onEvent [as handler] (/var/task/index.js:2593:13)
at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29) (RequestId: f1f649cb-284f-41df-ae21-02d6d76e0030)

This is when using node v18.18.2 and npm 9.5.1
Any ideas ?

**Comment by gdunkle** [comment]
@peegee123 What region are you attempting to deploy the spoke stack to?

**Comment by peegee123** [comment]
> @peegee123 What region are you attempting to deploy the spoke stack to?
eu-west-1
I'm using that region for everything at present.

**Comment by vibhamsharma** [comment]
Did we got any solution for this ?
